### ISSUE TITLE
Firefox のショートカットキーが機能しない

### ISSUE THREAD

**Issue by arigayas** [funnyface/niconicopitchchanger#9]
niconicopitchchanger が有効なニコニコ動画のHTML5プレイヤーがあるタブで以下のショートカットキーが機能しません。

- アドオン一覧を開く：Ctrl+Shift+A
- 履歴を開く：Ctrl+H
- すべての履歴を開く：Ctrl+Shift+H
- 最後に閉じたタブを開く：Ctrl+Shift+T
- ダウンロード一覧を開く：Ctrl+J
- ページ情報：Ctrl+I
- ファイルを開く：Ctrl+O
- ページを保存する：Ctrl+S
- ページを印刷する：Ctrl+P

など他多数というか疲れたので調査はここまでにします。

**Comment by funnyface** [comment]
v1.0.2にて対応済み
